config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:index, :show, :update] do
    resources :events
    resources :notifications, only: [:index, :show, :update, :destroy]
    resources :relations, only: [:index, :update, :destroy]
    get '/relations/new_caretaker', to: 'relations#new_caretaker', as: 'new_caretaker'
    post '/relations/new_caretaker', to: 'relations#create_caretaker', as: 'create_caretaker'
    get '/relations/new_patient', to: 'relations#new_patient', as: 'new_patient'
    post '/relations/new_patient', to: 'relations#create_patient', as: 'create_patient'
  end

  # to have a index events page (with all events caretaker and all patients)
  get '/events', to: 'events#full_index', as: "events"
  get '/notifications', to: 'notifications#full_index', as: "notifications"

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, :set_patients, :set_notifications, only: [:index, :show]
  before_action :set_profile, only: [:show, :edit]
  # skip_after_action :verify_policy_scoped, only: :index

  def index
    # geting user events
    set_events(@user)
    # geting all events for each patient
    @patients.each { |patient| @events += set_events(patient) }
    @events.sort_by { |start_time| start_time[:start_time]}
    # getting all pending requests
    set_pending_requests(@user)
  end

  def show
    authorize @profile, :edit?
    # geting events for this profile
    set_events(@profile)
    # geting notifications for this profile
    @notifications = @notifications.where(event_id: @events.pluck(:id)).order(created_at: :desc)
    set_pending_requests(@user)
  end

  def update
    @user = current_user
    authorize @user, :show?
    @user.simple_view ? @user.update(simple_view: false) : @user.update(simple_view: true)
    redirect_to profiles_path
  end

  private

  def set_user
    # set this user
    @user = current_user
  end

  def set_profile
    # get profile user
    @profile = User.find(params[:id])
  end

  def set_patients
    # get all patientes for current user
    @patients = policy_scope(@user.patients.where('relations.state = true'))
  end

  def set_notifications
    # get all notifications for current user only not dismissed and ordered by date
    @notifications = policy_scope(@user.notifications).where(dismissed: false).order(created_at: :desc)
  end

  def set_events(user)
    # get events with given user
    @events = policy_scope(user.events).order(start_time: :asc)
  end

  def set_pending_requests(user)
    @pendings = user.pending_caretaker_requests.where.not(sender_id: user.id)
    @pendings += user.pending_patient_requests.where.not(sender_id: user.id)
    @pendings = @pendings.empty?
  end
end

app/views/profiles/edit.html.erb
<h1>Edit page of <%= link_to @profile.email, profile_path(@profile) %></h1>
<%= link_to "Edit #{@profile.email} User", edit_user_registration_path if @user == @profile %>
<h2>Patients</h2>
<p><%= "No patients" if @patients.empty? %></p>
<% @patients.each do |patient| %>
  <p><%= link_to patient.email, profile_path(patient) %></p>
<% end %>
<h2>Caretakers</h2>
<p><%= "No caretackers" if @profile.caretakers.empty? %></p>
<% @profile.caretakers.each do |caretaker| %>
  <p><%= link_to caretaker.email, profile_path(caretaker) %></p>
<% end %>

app/views/profiles/index.html.erb
<% if @user.simple_view %>
  <div class="schedule-button-element">
    <%= link_to "Schedule", profile_events_path(@user), class: "schedule-button" %>
  </div>
  <div class="notification-button-element">
    <%= link_to "Notifications", profile_notifications_path(@user), class: "notification-button" %>
  </div>
<% else %>
  <div class="dashboard-container">
    <div class="profiles-list col-xs-12 col-md-4">
      <div class="profiles-list-header">
        <span>People</span>
      </div>
      <div class="profile-list-container" <%= "style='overflow-y: scroll;'" if @patients.size > 4 %> >
        <%=
          render 'shared/profile-card',
          user: @user,
          notifications: @notifications.where(event_id: @user.events.pluck(:id)).count %>
        <% @patients.each do |patient| %>
          <%=
            render 'shared/profile-card',
            user: patient,
            notifications: @notifications.where(event_id: patient.events.pluck(:id)).count
          %>
        <% end %>
      </div>
      <% unless @pendings %>
        <div class="btn-container-full-width">
          <%= link_to "New relation request", profile_relations_path(@user), class: "btn-orange" %>
        </div>
      <% end %>
    </div>
    <div class="notifications-list col-xs-12 col-md-4">
      <div class="notifications-list-header">
        <span>Latest Notifications</span>
      </div>
      <div class="notifications-list-container" <%= "style=overflow-y:scroll;" if @notifications.size > 5 %> >
        <% @notifications.each do |notification| %>
          <%= render 'shared/notification-card', notification: notification %>
        <% end %>
      </div>
      <div class="notifications-list-see-more">
        <% if @notifications.empty? %>
          <p>
            <strong>Yay!</strong> 🎉 you don't have any notifications.
          </p>
        <% end %>
        <% if @notifications.size > 5 %>
          <p>
            <%= link_to "See all notifications", notifications_path, class: "btn-blue" %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="events-list col-xs-12 col-md-4">
      <div class="events-list-header hidden-md hidden-lg">
        <p>Schedule</p>
      </div>
      <div class="events-list-container">
        <div>
          <%= render 'shared/calendar-day', profile: @user, events: @events %>
        </div>
        <div class="events-list-see-more">
        <%= if current_user.patients.empty?
            link_to "See your schedule", profile_events_path(current_user), class: "btn-blue"
          else
            link_to "See full schedule", events_path, class: "btn-blue"
          end %>
      </div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="dashboard-container">
  <div class="profiles-list col-xs-12 col-md-4">
    <div class="profiles-list-header">
      <span>People</span>
    </div>
    <div class="profiles-list-container">
      <%= render 'shared/profile-card', user: @profile, notifications: @notifications.count %>
    </div>
    <% if @pendings %>
      <div class="btn-container-full-width">
        <%= link_to "Edit relations", profile_relations_path(profile_id: @profile), class: "btn-blue" %>
      </div>
    <% else %>
      <div class="btn-container-full-width">
        <%= link_to "New relation request", profile_relations_path(@profile), class: "btn-orange" %>
      </div>
    <% end %>
    <% if @profile == current_user %>
      <div class="btn-container-full-width">
        <%= link_to "Edit my profile", edit_user_registration_path, class: "btn-blue" %>
      </div>
    <% end %>
  </div>
  <div class="notifications-list col-xs-12 col-md-4">
    <div class="notifications-list-header">
      <span>Latest Notifications</span>
    </div>
    <div class="notifications-list-container" <%= "style=overflow-y:scroll;" if @notifications.size > 5 %>>
      <% @notifications.each do |notification| %>
        <%= render 'shared/notification-card', notification: notification %>
      <% end %>
    </div>
    <div class="notifications-list-see-more">
      <% if @notifications.empty? %>
        <p>
          <strong>Yay!</strong> 🎉 you don't have any notifications.
        </p>
      <% end %>
      <% if @notifications.size > 5 %>
        <%= link_to "See #{@profile == current_user ? 'your' : @profile.first_name} notifications", profile_notifications_path(@profile), class: "btn-blue" %>
      <% end %>
    </div>
  </div>
  <div class="events-list col-xs-12 col-md-4">
    <div class="events-list-container">
      <%= render 'shared/calendar-day', events: @events %>
    </div>
    <div class="events-list-see-more">
      <%= link_to "Add event", new_profile_event_path(@profile), class: "btn-blue" %>
      <%= link_to "See #{@profile == current_user ? 'your' : @profile.first_name} schedule", profile_events_path(@profile), class: "btn-blue" %>
    </div>
  </div>
</div>