config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:index, :show, :update] do
    resources :events
    resources :notifications, only: [:index, :show, :update, :destroy]
    resources :relations, only: [:index, :update, :destroy]
    get '/relations/new_caretaker', to: 'relations#new_caretaker', as: 'new_caretaker'
    post '/relations/new_caretaker', to: 'relations#create_caretaker', as: 'create_caretaker'
    get '/relations/new_patient', to: 'relations#new_patient', as: 'new_patient'
    post '/relations/new_patient', to: 'relations#create_patient', as: 'create_patient'
  end

  # to have a index events page (with all events caretaker and all patients)
  get '/events', to: 'events#full_index', as: "events"
  get '/notifications', to: 'notifications#full_index', as: "notifications"

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/relation.rb
class Relation < ApplicationRecord
  attr_accessor :email
  belongs_to :caretaker, foreign_key: 'caretaker_id', class_name: 'User'
  belongs_to :patient, foreign_key: 'patient_id', class_name: 'User'

  # send wellcome email
  after_create :send_relation_request_email

  validates :caretaker, uniqueness: { scope: :patient }

  # permite fazer rel= Releation.create.....
  # rel.patient e rel.caretaker => User instance

  private

  def send_relation_request_email
    UserMailer.relation_request(self).deliver_now
  end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_user, :set_profile
  before_action :set_relation, only: [:update, :destroy]

  def index
    authorize @profile, :edit?
    set_notifications
    @caretaker_relations = @profile.caretaker_relationships.where(state: true)
    @patient_relations = @profile.patient_relationships.where(state: true)
    @pendings = @profile.pending_caretaker_requests.where.not(sender_id: @profile.id)
    @pendings += @profile.pending_patient_requests.where.not(sender_id: @profile.id)
  end

  def update
    authorize @profile, :edit?
    @relation.state = true
      if @relation.save
        redirect_to profile_relations_path(@profile),
        notice: "You accepted the relation"
      else
        redirect_to profile_relations_path(@profile),
        alert: "Ops! somthing whent wrong."
      end
  end

  def new_caretaker
    authorize @profile, :edit?
    @relation = Relation.new
  end

  def create_caretaker
    authorize @profile, :edit?
    # get email from input
    user_email = params.dig(:relation, :email)
    # find user for caretaker
    caretaker = User.find_by(email: user_email)
    # handle user not found
    if caretaker.nil?
      redirect_to profile_new_caretaker_path(@profile), alert: "User not found!"
    else
      relation = Relation.new(caretaker_id: caretaker.id, patient_id: @profile.id, state: false, sender_id: @profile.id)
      if relation.save
        redirect_to profile_relations_path(@profile),
        notice: "You sent a request to add #{caretaker.first_name} as caretaker"
      else
        redirect_to profile_new_caretaker_path(profile_id: @profile), alert: "#{caretaker.first_name} is already a caretaker!"
      end
    end
  end

  def new_patient
    authorize @profile, :edit?
    @relation = Relation.new
  end

  def create_patient
    authorize @profile, :edit?
    # get email from input
    user_email = params.dig(:relation, :email)
    # find user for caretaker
    patient = User.find_by(email: user_email)
    # handle user not found
    if patient.nil?
      redirect_to profile_new_patient_path(profile_id: @profile), alert: "User not found!"
    else
      relation = Relation.new(caretaker_id: @profile.id, patient_id: patient.id, state: false, sender_id: @profile.id)
      if relation.save
        redirect_to profile_relations_path(@profile),
        notice: "You sent a request to add #{patient.first_name} as patient"
      else
        redirect_to profile_new_patient_path(profile_id: @profile), alert: "#{patient.first_name} is already a patient!"
      end
    end
  end

  def destroy
    authorize @profile, :edit?
    if @relation.caretaker == @user
      if @relation.destroy
        redirect_to profiles_path,
        notice: "You deleted that relation."
      else
        redirect_to profile_relations_path(@profile),
        alert: "Ops! somthing whent wrong."
      end
    else
      if @relation.destroy
        redirect_to profile_relations_path(@profile),
        notice: "You deleted that relation."
      else
        redirect_to profile_relations_path(@profile),
        alert: "Ops! somthing whent wrong."
      end
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_profile
    @profile = User.find(params[:profile_id])
  end

  def set_relation
    @relation = Relation.find(params[:id])
  end

  def set_notifications
    # get all notifications for current user only not dismissed and ordered by date
    @notifications = policy_scope(@user.notifications).where(dismissed: false).order(created_at: :desc)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
end

app/views/relations/index.html.erb
<div class="relations-container">
  <div class="relations-caretakers-list col-xs-12 col-md-4">
    <div class="relations-caretakers-list-header">
      <span>Caretakers</span>
    </div>
    <div class="relations-caretaker-list-container">
      <% @caretaker_relations.each do |relation| %>
        <%=
          render 'shared/relation-card',
          user: relation.caretaker,
          relation: relation
        %>
      <% end %>
    </div>
    <div class="btn-container-full-width">
      <%= link_to "Add caretaker", profile_new_caretaker_path(@profile), class: "btn-blue" %>
    </div>
  </div>
  <div class="relations-patients-list col-xs-12 col-md-4">
    <div class="relations-patients-list-header">
      <span>Patients</span>
    </div>
    <div class="relations-patients-list-container">
      <% @patient_relations.each do |relation| %>
        <%=
          render 'shared/relation-card',
          user: relation.patient,
          relation: relation
        %>
      <% end %>
    </div>
    <div class="btn-container-full-width">
      <%= link_to "Add patient", profile_new_patient_path(@profile), class: "btn-blue" %>
    </div>
  </div>
  <div class="relations-pending-list col-xs-12 col-md-4">
    <div class="relations-pending-list-header">
      <span>Pending Requests</span>
    </div>
    <div class="relations-pending-list-container">
      <% @pendings.each do |relation| %>
        <%
          if relation.caretaker == @profile
            other_user = relation.patient
            role = 'Patient'
          else
            other_user = relation.caretaker
            role = 'Caretaker'
          end
        %>
        <%=
          render 'shared/relation-card',
          user: other_user,
          role: role,
          relation: relation
        %>
      <% end %>
    </div>
  </div>
</div>

app/views/relations/new_caretaker.html.erb
<div class="form-container full-height">
  <div class="form-card">
    <h1>New Caretaker</h1>
    <%= simple_form_for(@relation, url: profile_create_caretaker_path(@profile), method: 'post') do |f| %>
      <div class="form-inputs">
        <%= f.input :email,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Add Caretaker", class: "btn-blue" %>
      </div>
      <%= link_to 'Back to Profile', profile_path(@profile) %>
    <% end %>
  </div>
</div>

app/views/relations/new_patient.html.erb
<div class="form-container full-height">
  <div class="form-card">
    <h1>New Patient</h1>
    <%= simple_form_for(@relation, url: profile_create_patient_path(@profile), method: 'post') do |f| %>
      <div class="form-inputs">
        <%= f.input :email,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Add Patient", class: "btn-blue" %>
      </div>
      <%= link_to 'Back to Profile', profile_path(@profile) %>
    <% end %>
  </div>
</div>