config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:index, :show, :update] do
    resources :events
    resources :notifications, only: [:index, :show, :update, :destroy]
    resources :relations, only: [:index, :update, :destroy]
    get '/relations/new_caretaker', to: 'relations#new_caretaker', as: 'new_caretaker'
    post '/relations/new_caretaker', to: 'relations#create_caretaker', as: 'create_caretaker'
    get '/relations/new_patient', to: 'relations#new_patient', as: 'new_patient'
    post '/relations/new_patient', to: 'relations#create_patient', as: 'create_patient'
  end

  # to have a index events page (with all events caretaker and all patients)
  get '/events', to: 'events#full_index', as: "events"
  get '/notifications', to: 'notifications#full_index', as: "notifications"

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_calendar-day.html.erb
<div class="calendar-day">
  <%= calendar number_of_days: 1, events: events do |date, events| %>
    <div <%= "style=overflow-y:scroll;height:452px;" if events.size > 5 %>>
      <% events.each do |event| %>
        <div class="calendar-day-event">
          <%= link_to "", profile_event_path(event.user, event), class: "calendar-day-event-link" %>
          <p><i class="fas <%=event.event_type.description%>"></i><strong><%=" " +  event.name %></strong></p>
          <span>
            <%= event.start_time.strftime("%H:%M") %>
            <%= " | " %>
            <%= event.user == current_user ? "You" : event.user.first_name %>
          </span>
        </div>
      <% end %>
    </div>
    <div class="events-list-see-more">
      <% if events.empty? %>
        <p>
          <strong>Ooh!</strong> 🤔 you don't have any events.
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_calendar-week.html.erb
<div class="calendar-week">
  <%= week_calendar number_of_weeks: 1, events: events do |date, events| %>
    <% events.each do |event| %>
      <div class="calendar-week-event">
        <%= link_to "", profile_event_path(event.user, event), class: "calendar-day-event-link" %>
        <p><i class="fas <%=event.event_type.description%>"></i><strong><%= " " + event.name %></strong></p>
        <span>
          <%= event.start_time.strftime("%H:%M") %>
          <%= " | " %>
          <%= event.user == current_user ? "You" : event.user.first_name %>
        </span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links col-xs-12 col-md-6">
    <a href="https://www.facebook.com/caretaker4life" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/caretaker4life" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://github.com/RuiSMagalhaes/rails-Caretaker" target="_blank"><i class="fab fa-github"></i></a>
    <a href="mailto:support@caretaker.pt" target="_blank"><i class="fas fa-envelope"></i></a>
  </div>
  <div class="footer-copyright col-xs-12 col-md-6">
    <i class="far fa-copyright"></i> CARETAKER | Helper for life | <%= Time.now.to_date.year %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar-caretaker">
    <!-- left side -->
    <div class="navbar-caretaker-left hidden-xs hidden-sm">
      <!-- nothing inside -->
    </div>
    <!-- Logo -->
    <%= link_to profiles_path, class: "navbar-caretaker-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-caretaker-right">
      <div class="navbar-caretaker-right-links hidden-xs hidden-sm">
        <!-- Links when logged in -->
        <% if current_user.simple_view  %>
        <% elsif current_user.patients.empty?   %>
          <%= link_to "Dashboard", profiles_path, class: "navbar-caretaker-item navbar-caretaker-link" %>
          <%= link_to "Events", profile_events_path(current_user), class: "navbar-caretaker-item navbar-caretaker-link" %>
          <%= link_to "Notifications", profile_notifications_path(current_user), class: "navbar-caretaker-item navbar-caretaker-link" %>
        <%else %>
          <%= link_to "Dashboard", profiles_path, class: "navbar-caretaker-item navbar-caretaker-link" %>
          <%= link_to "Events", events_path, class: "navbar-caretaker-item navbar-caretaker-link" %>
          <%= link_to "Notifications", notifications_path, class: "navbar-caretaker-item navbar-caretaker-link" %>
          <%#= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-caretaker-item navbar-caretaker-link" %>
        <% end %>
      </div>

      <!-- Dropdown list -->
      <% if current_user.simple_view %>
        <div class="navbar-caretaker-item">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-caretaker-dropdown-menu">
              <li><%= link_to "Change View", profile_path(current_user), method: :patch, clas: "hidden-md hidden-lg" %></li>
            </ul>
          </div>
        </div>
      <%elsif  current_user.patients.empty?  %>
        <div class="navbar-caretaker-item">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-caretaker-dropdown-menu">
              <li><a class="hidden-md hidden-lg" href="<%= profiles_path %>">Dashboard</a></li>
              <li><a class="hidden-md hidden-lg" href="<%= profile_events_path(current_user)%>">Events</a></li>
              <li><a class="hidden-md hidden-lg" href="<%= profile_notifications_path(current_user) %>">Notifications</a></li>
              <li><%= link_to "Change View", profile_path(current_user), method: :patch, clas: "hidden-md hidden-lg" %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="navbar-caretaker-item">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-caretaker-dropdown-menu">
              <li><a class="hidden-md hidden-lg" href="<%= profiles_path %>">Dashboard</a></li>
              <li><a class="hidden-md hidden-lg" href="<%= events_path %>">Events</a></li>
              <li><a class="hidden-md hidden-lg" href="<%= notifications_path %>">Notifications</a></li>
              <li><%= link_to "Change View", profile_path(current_user), method: :patch, clas: "hidden-md hidden-lg" %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <!-- no navbar if not sign in -->
<% end %>

app/views/shared/_notification-card.html.erb
<%
  # logic to get class for each notification type and for word before time
  notification_type = notification.notification_type
  if notification_type == "missed"
    type_class = "notification-flash-danger"
    type = "Missed"
  elsif notification_type == "done"
    type_class = "notification-flash-success"
    type = "Done"
  elsif notification_type == "before"
    type_class = "notification-flash-warning"
    type = "Scheduled"
  elsif notification_type == "do"
    type_class = "notification-flash-do"
    type = "Scheduled"
  else
    type_class = "notification-flash-normal"
    type = ""
  end
%>

<div class='notification-flash <%= type_class %>'>
  <%= link_to "", profile_notification_path(notification.event.user, notification), class: "notification-flash-link" %>
  <div class="notification-flash-content">
    <p><i class="fas <%=notification.event.event_type.description%>"></i><strong><%=" " + notification.event.name %></strong></p>
    <span><%= type %> <%= notification.event.start_time.strftime('At %H:%M') %> | <%=
    notification.event.user == current_user ? "You" : notification.event.user.first_name %></span>
  </div>
  <%= link_to profile_notification_path(notification.event.user, notification), method: :delete, data: { confirm: 'Dismiss Notification?' }, class: "dismiss" do %>
    <i class="fas fa-times"></i>
  <% end %>
</div>

app/views/shared/_notification_before.html.erb
<!-- Notification for Caretakers and for Users of the event -->
<div class="card-notification-before">
  <div class="notification-infos">
    <div class="notification-title">
        <% if @notification.event.user == current_user %>
          <p>For you</p>
        <%else %>
          <p><%="For " + @notification.event.user.first_name + " " + @notification.event.user.last_name  %></p>
        <% end %>
    </div>
    <div class="notification-infos-event">
      <!-- Change this image for the one of notification.event.event_type.description -->
      <!-- <img src="#" class="info-event-type"> -->
      <div class="info-event-name-time">
        <h5><i class="fas <%=@notification.event.event_type.description%>"></i><%= " " + @notification.event.name %> </h5>
        <p> <%= @notification.event.start_time.strftime('At %H:%M') %> </p>
      </div>
    </div>
    <div class="item-description">
      <p><%= @notification.event.description %></p>
    </div>
    <div class="buttons">
      <% unless @notification.event.done %>
        <% if @notification.event.user == current_user %>
          <%= link_to profile_notification_path(@notification.event.user, @notification), method: :patch, class: "no-decoration" do %>
            <p class="button-done">Mark as done</p>
          <% end %>
        <% end %>
      <% end %>
      <% unless @notification.dismissed %>
        <%= link_to profile_notification_path(@notification.event.user, @notification), method: :delete, class: "no-decoration" do %>
          <p class="button-dismiss">Dismiss</p>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to profiles_path, class: "btn-close" do %>
    <i class="far fa-times-circle"></i>
  <% end %>
</div>

app/views/shared/_notification_do.html.erb
<!-- Notification only for Users of the event -->
<div class="card-notification-do">
  <div class="notification-infos">
    <div class="notification-title">
      <p>For you</p>
    </div>
    <div class="notification-infos-event">
      <!-- Change this image for the one of notification.event.event_type.description -->
      <!-- <img src="#" class="info-event-type"> -->
      <div class="info-event-name-time">
        <h5><i class="fas <%=@notification.event.event_type.description%>"></i><%= " " + @notification.event.name %> </h5>
        <p> <%= @notification.event.start_time.strftime('At %H:%M') %> </p>
      </div>
    </div>
    <div class="item-description">
      <p><%= @notification.event.description %></p>
    </div>
    <div class="buttons">
      <% unless @notification.event.done%>
        <%= link_to profile_notification_path(@notification.event.user, @notification), method: :patch, class: "no-decoration" do %>
          <p class="button-done">Mark as done</p>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to profiles_path, class: "btn-close" do %>
    <i class="far fa-times-circle"></i>
  <% end %>
</div>

app/views/shared/_notification_done.html.erb
<!-- Notification only to caretakers -->
<div class="card-notification-done">
  <div class="notification-infos">
    <div class="notification-title">
      <p><%="For " +  @notification.event.user.first_name + " " + @notification.event.user.last_name  %></p>
    </div>
    <div class="notification-infos-event">
      <!-- Change this image for the one of notification.event.event_type.description -->
      <!-- <img src="#" class="info-event-type"> -->
      <div class="info-event-name-time">
        <h5><i class="fas <%=@notification.event.event_type.description%>"></i><%=" " + @notification.event.name %> </h5>
        <p> <%= @notification.event.start_time.strftime('At %H:%M') %> </p>
      </div>
    </div>
    <div class="item-description">
      <p><%= @notification.event.description %></p>
    </div>
    <div class="buttons">
      <% unless @notification.dismissed %>
          <%= link_to profile_notification_path(@notification.event.user, @notification), method: :delete, class: "no-decoration" do %>
            <p class="button-dismiss">Dismiss</p>
          <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to profiles_path, class: "btn-close" do %>
    <i class="far fa-times-circle"></i>
  <% end %>
</div>

app/views/shared/_notification_missed.html.erb
<!-- Notification for Caretakers and for Users of the event -->
<div class="card-notification-missed">
  <div class="notification-infos">
    <div class="notification-title">
        <% if @notification.event.user == current_user %>
          <p>For you</p>
        <%else %>
          <p><%= "For " + @notification.event.user.first_name + " " + @notification.event.user.last_name  %></p>
        <% end %>
    </div>
    <div class="notification-infos-event">
      <!-- Change this image for the one of notification.event.event_type.description -->
      <!-- <img src="#" class="info-event-type"> -->
      <div class="info-event-name-time">
        <h5><i class="fas <%=@notification.event.event_type.description%>"></i><%=" " + @notification.event.name %> </h5>
        <p> <%= @notification.event.start_time.strftime('At %H:%M') %> </p>
      </div>
    </div>
    <div class="item-description">
      <p><%= @notification.event.description %></p>
    </div>
    <div class="buttons">
      <% unless @notification.event.done %>
        <% if @notification.event.user == current_user %>
          <%= link_to profile_notification_path(@notification.event.user, @notification), method: :patch, class: "no-decoration" do %>
            <p class="button-done">Mark as done</p>
          <% end %>
        <% end %>
      <% end %>
      <% unless @notification.dismissed %>
        <% if @notification.event.user != current_user %>
          <%= link_to profile_notification_path(@notification.event.user, @notification), method: :delete, class: "no-decoration" do %>
            <p class="button-dismiss">Dismiss</p>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to profiles_path, class: "btn-close" do %>
    <i class="far fa-times-circle"></i>
  <% end %>
</div>

app/views/shared/_profile-card.html.erb
<div class="profile-card">
  <%= link_to "", profile_path(user), class: "profile-card-link" %>
  <img src='<%= cloudinary_url(user.photo) %>' class="avatar-large"/>
  <div class="profile-card-content">
    <h4><%= user.first_name %></h4>
    <p><small><%= user == current_user ? "You" : "Patient" %></small></p>
  </div>
  <% if !notifications.zero? %>
    <div class="profile-card-notifications-badge">
      <p><strong><%= notifications %></strong></p>
    </div>
  <% end %>
</div>

app/views/shared/_relation-card.html.erb
<div class="relation-card">
  <%= link_to "", profile_path(user), class: "relation-card-link" if relation.state %>
  <img src='<%= cloudinary_url(user.photo) %>' class="avatar-large"/>
  <div class="relation-card-content">
    <h4><%= user.first_name %></h4>
    <p><small><%= 'As: ' + role if !relation.state %></small></p>
  </div>
  <% if relation.state %>
    <%= link_to profile_relation_path(@profile, relation), method: :delete, data: { confirm: 'Are you sure?' }, class: "relation-card-action-delete" do %>
      <i class="far fa-times-circle"></i>
    <% end %>
  <% else %>
    <%= link_to profile_relation_path(@profile, relation), method: :patch, data: { confirm: 'Are you sure?' }, class: "relation-card-action-accept" do %>
      <i class="far fa-check-circle"></i>
    <% end %>
    <%= link_to profile_relation_path(@profile, relation), method: :delete, data: { confirm: 'Are you sure?' }, class: "relation-card-action-delete" do %>
      <i class="far fa-times-circle"></i>
    <% end %>
  <% end %>
</div>