config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles, only: [:index, :show, :update] do
    resources :events
    resources :notifications, only: [:index, :show, :update, :destroy]
    resources :relations, only: [:index, :update, :destroy]
    get '/relations/new_caretaker', to: 'relations#new_caretaker', as: 'new_caretaker'
    post '/relations/new_caretaker', to: 'relations#create_caretaker', as: 'create_caretaker'
    get '/relations/new_patient', to: 'relations#new_patient', as: 'new_patient'
    post '/relations/new_patient', to: 'relations#create_patient', as: 'create_patient'
  end

  # to have a index events page (with all events caretaker and all patients)
  get '/events', to: 'events#full_index', as: "events"
  get '/notifications', to: 'notifications#full_index', as: "notifications"

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :notifications

  after_create :job_event_to_notification
  # before_create :date_range, :start_date

  belongs_to :user
  belongs_to :event_type

  has_many :notifications, dependent: :destroy
  validate :date_range, :start_date, on: [:create]

  validates :name, :description, :start_time, :end_time, presence: true

  private

  def date_range
    errors.add(:end_time, ' can not be before Start time.') if end_time.nil? || (end_time < start_time)
  end

  def start_date
    errors.add(:start_time, ' can not be before current time.') if start_time.nil? || start_time < Time.now
  end

  def job_event_to_notification
    # Call a Job for the user of the event (event.user) to notify (type:DO) him on time = event.start_time (if event.done == false => see this only in the job)
    NotifyEventUserDoJob.set(wait_until: self.start_time).perform_later(self.id)
    # If notify_before is true, the user of the event has to be notified as well as all his caretakers
    if self.notify_before
      # TODO: Call a Job to create a notification to the user and to his caretakers some time (defined by event.minutes) before the event.start_time
      # if a user do not populate the minutes field, it's 15min as a default. this notification will pop up 15 min before the start time of the event
      self.minutes = 15 if self.minutes.nil?
      if self.start_time - self.minutes.minutes < Time.now
        NotifyCaretakerAndEventUserBeforeJob.perform_later(self.id)
      else
      # call the Job the the caretakers of the user and for the user of the event
        NotifyCaretakerAndEventUserBeforeJob.set(wait_until: self.start_time - self.minutes.minutes).perform_later(self.id)
      end
    end
    # If notify_missed is true, the user of the event has to be notified as well as all his caretakers
    # TODO: Call a Job to create notifications for the user of the event his caretakers 15 minutes after the event.start_time (if done == false => check this on the Job only)
    NotifyCaretakerAndEventUserMissedJob.set(wait_until: self.start_time + 15.minutes).perform_later(self.id) if self.notify_missed
    # if notify_done is true, all the caretakers of the user of the event need to be notified when the user of the event press the button "Done"
    # this logic is on the notification controller
  end
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user
  before_action :set_profile, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_event, :set_events, only: [:show, :edit, :update, :destroy]

  def index
    authorize @profile, :show?
    set_events
  end

  def full_index
    authorize @user, :edit?
    # geting user events
    @events = set_all_events(@user)
    # set patients
    @patients = set_patients
    # geting all events for each patient
    @patients.each { |patient| @events += set_all_events(patient) }
  end

  def show
    authorize @profile, :show?
  end

  # GET /events/new
  def new
    authorize @profile, :edit?
    @event = Event.new
  end

  def create
    authorize @profile, :edit?
    # create new event with params from form
    @event = Event.new(event_params)
    # call create first event to process at least one event
    create_first(@event)
  end

  def edit
    authorize @profile, :edit?
    # select the first event of a series of events so the displayed info relates to the first one
    @event = @events.where(start_id: @event.start_id).first
  end

  def update
    authorize @profile, :edit?
    # select all events with the start id
    @events = @events.where(start_id: @event.start_id)
    # clean db so previous events will removed
    @events.destroy_all
    # create new event with params from form
    @event = Event.new(event_params)
    # call create first event to process at least one event
    create_first(@event)
  end

  def destroy
    authorize @profile, :edit?
    # destroy all events with the same start id
    @events.where(start_id: @event.start_id).destroy_all
    redirect_to profile_events_path(@profile), notice: 'Event was successfully destroyed.'
  end

  private

  def set_user
    @user = current_user
  end

  def set_profile
    @profile = User.find(params[:profile_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_events
    # get events with given user
    @events = policy_scope(@profile.events)
  end

  def set_patients
    # get all patientes for current user
    @patients = policy_scope(@user.patients)
  end

  def set_all_events(user)
    # get events with given user
    @events = user.events
  end

  def create_first(event)
    # add profile user to the event
    @event = event
    @event.user = @profile
    # validation if saved
    if @event.save
      # add start_id to event
      @event.update(start_id: @event.id)
      # call creation of multiple events
      create_multiple(@event) if @event.recurring
      # redirect to event
      redirect_to profile_events_path(@profile), notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def create_multiple(event)
    # defining number of times that event is recurring
    times = event.recurring_times - 1
    # run the event save until number of times is 0
    until times.zero?
      # duplicate last event added
      next_event = event.dup
      # define hours, days, weeks and months
      next_event.hours.nil? ? hours = 0.hours : hours = next_event.hours.hours
      next_event.days.nil? ? days = 0.days : days = next_event.days.days
      next_event.weeks.nil? ? weeks = 0.weeks : weeks = next_event.weeks.weeks
      next_event.months.nil? ? months = 0.months : months = next_event.months.months
      # sum the time space to start_time and end_time
      next_event.start_time = next_event.start_time + hours + days + weeks + months
      next_event.end_time = next_event.end_time + hours + days + weeks + months
      # save event to db
      next_event.save
      # define the event as the last saved event
      event = next_event
      # remove on time from iteration
      times -= 1
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name,
                                  :description,
                                  :start_time,
                                  :user_id,
                                  :event_type_id,
                                  :end_time,
                                  :recurring,
                                  :recurring_times,
                                  :notify_before,
                                  :notify_done,
                                  :done,
                                  :notify_missed,
                                  :minutes,
                                  :hours,
                                  :days,
                                  :weeks,
                                  :months)
  end
end

app/views/events/_calendar.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<div class="calendar-day">
  <%= calendar number_of_days: 1, events: @events do |date, events| %>
    <% events.each do |event| %>
      <div>
        <p><%= event.start_time.strftime("%H:%M") %> | <%= link_to event.name, profile_event_path(event.user, event) %></p>
      </div>
    <% end %>
  <% end %>
</div>

<div class="calendar-week">
  <%= week_calendar number_of_weeks: 1, events: @events do |date, events| %>
    <% events.each do |event| %>
      <div>
        <p><%= event.start_time.strftime("%H:%M") %> | <%= link_to event.name, profile_event_path(event.user, event) %></p>
      </div>
    <% end %>
  <% end %>
</div>

<%= month_calendar events: @events do |date, events| %>
  <%= date %>
  <% events.each do |event| %>
    <div>
      <p><%= event.name %></p>
    </div>
  <% end %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.start_time %></td>
        <td><%= link_to 'Show', profile_event_path(event.user, event) %></td>
        <td><%= link_to 'Edit', edit_profile_event_path(event.user, event) %></td>
        <td><%= link_to 'Destroy', profile_event_path(event.user, event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_profile_event_path(@user) %>

app/views/events/_events-list.html.erb
<div class="events-all-conatiner">
  <div class="events-all-header">
    <h3>
      <% if @profile.nil? %>
        Full schedule
      <% elsif @profile == current_user %>
        Your schedule
      <% else %>
        <%= "#{@profile.first_name}'s" %> schedule
      <% end %>
    </h3>
  </div>
  <% unless current_user.patients.empty? || current_user.simple_view  %>
    <div class="events-all-filters closed">
      <% if @profile.nil? %>
        <div class="events-all-filters-button col-xs-12 col-md-6">
          <%= link_to "Your events", profile_events_path(@user), class: "btn-blue" %>
        </div>
      <% else %>
        <div class="events-all-filters-button col-xs-12 col-md-6">
          <%= link_to "All events", events_path, class: "btn-blue" %>
        </div>
        <% unless @user == @profile %>
          <div class="events-all-filters-button col-xs-12 col-md-6">
            <%= link_to "Your events", profile_events_path(@user), class: "btn-blue" %>
          </div>
        <% end %>
      <% end %>
      <% @user.patients.each do |patient| %>
        <% unless patient == @profile %>
          <div class="events-all-filters-button col-xs-12 col-md-6">
            <%= link_to "#{patient.first_name}'s' events", profile_events_path(patient), class: "btn-blue" %>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= link_to "More patients", '#', id: "show-more" if @user.patients.size > 1 %>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= f.error_notification %>
<%= f.error_notification message: @event.errors.full_messages.to_sentence %>

<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :description  %>
  <%= f.association :event_type %>
  <%= f.input :start_time,
              as: :string %>
  <%= f.input :end_time,
              as: :string %>
  <%= f.input :notifications, as: :boolean,
              hint:"  Manage notifications." %>
  <%= f.input :notify_before?, as: :boolean,
              wrapper_html: {class:'hidden' },
              hint:"  Notify before the event." %>
  <%= f.input :minutes,
              collection: [15,30,45],
              wrapper_html: {class:'hidden' },
              hint:"  Notifications time before the event (default 15mins)." %>
  <%= f.input :notify_done?, as: :boolean,
              wrapper_html: {class:'hidden' },
              hint:"  Notify caretaker(s) when event is done." %>
  <%= f.input :notify_missed?, as: :boolean,
              wrapper_html: {class:'hidden' },
              hint:"  Notify 15mins after the scheduled time." %>
  <%= f.input :recurring?, as: :boolean,
              hint:"  If event happen multiple times." %>
  <%= f.input :recurring_times,
              wrapper_html: {class:'hidden' },
              collection: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],
              hint:"  Number of times the event happen." %>
  <%= f.input :hours,
              wrapper_html: {class:'hidden' },
              collection: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],
              hint:"  Hours between events." %>
  <%= f.input :days,
              wrapper_html: {class:'hidden' },
              collection: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],
              hint:"  Days between events." %>
  <%= f.input :weeks,
              wrapper_html: {class:'hidden' },
              collection: [1,2,3,4],
              hint:"  Weeks between events." %>
  <%= f.input :months,
              wrapper_html: {class:'hidden' },
              collection: [1,2,3,4,5,6,7,8,9,10,11],
              hint:"  Months between events." %>
</div>

<div class="form-actions">
  <%= f.button :submit, class:'btn-blue' %>
</div>

app/views/events/edit.html.erb
<div class="form-container">
  <div class="form-card">
    <h1>Edit Event</h1>
    <%= simple_form_for(@event, url: profile_event_path(@profile), method: 'patch') do |f| %>
      <%= render 'form', f: f %>
    <% end %>
    <%= link_to 'Back to Event', profile_event_path(@profile, @event) %> |
    <%= link_to 'Back to Schedule', profile_events_path(@profile) %>
  </div>
</div>

app/views/events/full_index.html.erb
<%= render 'events-list' %>
<div class="events-list hidden-md hidden-lg">
  <div><%= render 'shared/calendar-day', events: @events %></div>
</div>
<div class="events-list hidden-xs hidden-sm">
  <div><%= render 'shared/calendar-week', events: @events %></div>
</div>

app/views/events/index.html.erb
<%=  render 'events-list' %>
<div class="events-list hidden-md hidden-lg">
  <div><%= render 'shared/calendar-day', events: @events %></div>
</div>
<div class="events-list hidden-xs hidden-sm">
  <div><%= render 'shared/calendar-week', events: @events %></div>
</div>
<%=  unless current_user.simple_view
   link_to "Add Event", new_profile_event_path(@profile), class: "btn-blue"
    end %>

app/views/events/new.html.erb
<div class="form-container">
  <div class="form-card">
    <h1>New Event</h1>
    <%= simple_form_for(@event, url: profile_events_path(@profile), method: 'post') do |f| %>
      <%= render 'form', f: f %>
    <% end %>
    <%= link_to 'Back to Schedule', profile_events_path(@profile) %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-container full-height">
  <div class="event-card">
    <div class="event-title">
      <% if @event.user == current_user %>
        <p>For you</p>
      <%else %>
        <p><%="For " + @event.user.first_name + " " + @event.user.last_name  %></p>
      <% end %>
    </div>
    <div class="event-infos-event">
      <!-- Change this image for the one of event.event.event_type.description -->
      <!-- <img src="#" class="info-event-type"> -->
      <div class="info-event-name-time">
        <h5><i class="fas <%=@event.event_type.description%>"></i><%= " " + @event.name %> </h5>
        <p> <%= @event.start_time.strftime('At %H:%M') %> </p>
      </div>
    </div>
    <div class="item-description">
      <p><%= @event.description %></p>
    </div>
    <% unless @user.simple_view %>
      <div class="btn-container-full-width">
        <%= link_to "Edit", edit_profile_event_path(@profile, @event), class: "btn-blue" %>
      </div>
      <div class="btn-container-full-width">
        <%= link_to "Delete", profile_event_path(@profile, @event), method: :delete, class: "btn-red", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <%= link_to profile_events_path(@profile), class: "btn-close" do %>
      <i class="far fa-times-circle"></i>
    <% end %>
  </div>
</div>